image: jhipster/jhipster:v6.1.2

cache:
    key: '$CI_COMMIT_REF_NAME'
    paths:
        - .gradle/
stages:
    - build
    - test
    - analyze
    - package
    - release
    - deploy

before_script:
    - export NG_CLI_ANALYTICS="false"
    - export GRADLE_USER_HOME=`pwd`/.gradle

# gateway
gateway-gradle-compile:
    stage: build
    script:
        - cd /builds/kp.marczynski/dietify/gateway
        - sh gradlew npm_install -PnodeInstall --no-daemon
        - sh gradlew compileJava -x check -PnodeInstall --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        paths:
            - /builds/kp.marczynski/dietify/gateway/build/classes/
            - /builds/kp.marczynski/dietify/gateway/build/generated/
        expire_in: 1 day

gateway-gradle-test:
    stage: test
    script:
        - cd /builds/kp.marczynski/dietify/gateway
        - sh gradlew test -PnodeInstall --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        reports:
            junit: /builds/kp.marczynski/dietify/gateway/build/test-results/test/TEST-*.xml
        paths:
            - /builds/kp.marczynski/dietify/gateway/build/test-results/
            - /builds/kp.marczynski/dietify/gateway/build/jacoco/
        expire_in: 1 day

gateway-gradle-integration-test:
    stage: test
    script:
        - cd /builds/kp.marczynski/dietify/gateway
        - sh gradlew integrationTest -PnodeInstall --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        reports:
            junit: /builds/kp.marczynski/dietify/gateway/build/test-results/integrationTest/TEST-*.xml
        paths:
            - /builds/kp.marczynski/dietify/gateway/build/test-results/
            - /builds/kp.marczynski/dietify/gateway/build/jacoco/
        expire_in: 1 day

gateway-frontend-test:
    stage: test
    script:
        - cd /builds/kp.marczynski/dietify/gateway
        - sh gradlew npm_install -PnodeInstall --no-daemon
        - sh gradlew npm_run_test -PnodeInstall --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        reports:
            junit: /builds/kp.marczynski/dietify/gateway/build/test-results/TESTS-results-jest.xml
        paths:
            - /builds/kp.marczynski/dietify/gateway/build/test-results/
            - /builds/kp.marczynski/dietify/gateway/build/jacoco/
        expire_in: 1 day

gateway-gradle-package:
    stage: package
    script:
        - cd /builds/kp.marczynski/dietify/gateway
        - sh gradlew bootJar -Pprod -x check --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        paths:
            - /builds/kp.marczynski/dietify/gateway/build/libs/*.jar
            - /builds/kp.marczynski/dietify/gateway/build/classes
        expire_in: 1 day

# products
products-gradle-compile:
    stage: build
    script:
        - cd /builds/kp.marczynski/dietify/products
        - sh gradlew compileJava -x check -PnodeInstall --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        paths:
            - /builds/kp.marczynski/dietify/products/build/classes/
            - /builds/kp.marczynski/dietify/products/build/generated/
        expire_in: 1 day

products-gradle-test:
    stage: test
    script:
        - cd /builds/kp.marczynski/dietify/products
        - sh gradlew test -PnodeInstall --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        reports:
            junit: /builds/kp.marczynski/dietify/products/build/test-results/test/TEST-*.xml
        paths:
            - /builds/kp.marczynski/dietify/products/build/test-results/
            - /builds/kp.marczynski/dietify/products/build/jacoco/
        expire_in: 1 day

products-gradle-integration-test:
    stage: test
    script:
        - cd /builds/kp.marczynski/dietify/products
        - sh gradlew integrationTest -PnodeInstall --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        reports:
            junit: /builds/kp.marczynski/dietify/products/build/test-results/integrationTest/TEST-*.xml
        paths:
            - /builds/kp.marczynski/dietify/products/build/test-results/
            - /builds/kp.marczynski/dietify/products/build/jacoco/
        expire_in: 1 day

products-gradle-package:
    stage: package
    script:
        - cd /builds/kp.marczynski/dietify/products
        - sh gradlew bootJar -Pprod -x check --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        paths:
            - /builds/kp.marczynski/dietify/products/build/libs/*.jar
            - /builds/kp.marczynski/dietify/products/build/classes
        expire_in: 1 day

# recipes
recipes-gradle-compile:
    stage: build
    script:
        - cd /builds/kp.marczynski/dietify/recipes
        - sh gradlew compileJava -x check -PnodeInstall --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        paths:
            - /builds/kp.marczynski/dietify/recipes/build/classes/
            - /builds/kp.marczynski/dietify/recipes/build/generated/
        expire_in: 1 day

recipes-gradle-test:
    stage: test
    script:
        - cd /builds/kp.marczynski/dietify/recipes
        - sh gradlew test -PnodeInstall --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        reports:
            junit: /builds/kp.marczynski/dietify/recipes/build/test-results/test/TEST-*.xml
        paths:
            - /builds/kp.marczynski/dietify/recipes/build/test-results/
            - /builds/kp.marczynski/dietify/recipes/build/jacoco/
        expire_in: 1 day

recipes-gradle-integration-test:
    stage: test
    script:
        - cd /builds/kp.marczynski/dietify/recipes
        - sh gradlew integrationTest -PnodeInstall --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        reports:
            junit: /builds/kp.marczynski/dietify/recipes/build/test-results/integrationTest/TEST-*.xml
        paths:
            - /builds/kp.marczynski/dietify/recipes/build/test-results/
            - /builds/kp.marczynski/dietify/recipes/build/jacoco/
        expire_in: 1 day

recipes-gradle-package:
    stage: package
    script:
        - cd /builds/kp.marczynski/dietify/recipes
        - sh gradlew bootJar -Pprod -x check --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        paths:
            - /builds/kp.marczynski/dietify/recipes/build/libs/*.jar
            - /builds/kp.marczynski/dietify/recipes/build/classes
        expire_in: 1 day

# mealplans
mealplans-gradle-compile:
    stage: build
    script:
        - cd /builds/kp.marczynski/dietify/mealplans
        - sh gradlew compileJava -x check -PnodeInstall --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        paths:
            - /builds/kp.marczynski/dietify/mealplans/build/classes/
            - /builds/kp.marczynski/dietify/mealplans/build/generated/
        expire_in: 1 day

mealplans-gradle-test:
    stage: test
    script:
        - cd /builds/kp.marczynski/dietify/mealplans
        - sh gradlew test -PnodeInstall --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        reports:
            junit: /builds/kp.marczynski/dietify/mealplans/build/test-results/test/TEST-*.xml
        paths:
            - /builds/kp.marczynski/dietify/mealplans/build/test-results/
            - /builds/kp.marczynski/dietify/mealplans/build/jacoco/
        expire_in: 1 day

mealplans-gradle-integration-test:
    stage: test
    script:
        - cd /builds/kp.marczynski/dietify/appointments
        - sh gradlew integrationTest -PnodeInstall --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        reports:
            junit: /builds/kp.marczynski/dietify/mealplans/build/test-results/integrationTest/TEST-*.xml
        paths:
            - /builds/kp.marczynski/dietify/mealplans/build/test-results/
            - /builds/kp.marczynski/dietify/mealplans/build/jacoco/
        expire_in: 1 day

mealplans-gradle-package:
    stage: package
    script:
        - cd /builds/kp.marczynski/dietify/mealplans
        - sh gradlew bootJar -Pprod -x check --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        paths:
            - /builds/kp.marczynski/dietify/mealplans/build/libs/*.jar
            - /builds/kp.marczynski/dietify/mealplans/build/classes
        expire_in: 1 day

# appointments
appointments-gradle-compile:
    stage: build
    script:
        - cd /builds/kp.marczynski/dietify/appointments
        - sh gradlew compileJava -x check -PnodeInstall --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        paths:
            - /builds/kp.marczynski/dietify/appointments/build/classes/
            - /builds/kp.marczynski/dietify/appointments/build/generated/
        expire_in: 1 day

appointments-gradle-test:
    stage: test
    script:
        - cd /builds/kp.marczynski/dietify/appointments
        - sh gradlew test -PnodeInstall --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        reports:
            junit: /builds/kp.marczynski/dietify/appointments/build/test-results/test/TEST-*.xml
        paths:
            - /builds/kp.marczynski/dietify/appointments/build/test-results/
            - /builds/kp.marczynski/dietify/appointments/build/jacoco/
        expire_in: 1 day

appointments-gradle-integration-test:
    stage: test
    script:
        - cd /builds/kp.marczynski/dietify/appointments
        - sh gradlew integrationTest -PnodeInstall --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        reports:
            junit: /builds/kp.marczynski/dietify/appointments/build/test-results/integrationTest/TEST-*.xml
        paths:
            - /builds/kp.marczynski/dietify/appointments/build/test-results/
            - /builds/kp.marczynski/dietify/appointments/build/jacoco/
        expire_in: 1 day

appointments-gradle-package:
    stage: package
    script:
        - cd /builds/kp.marczynski/dietify/appointments
        - sh gradlew bootJar -Pprod -x check --no-daemon
    except:
        - praca-dyplomowa
    artifacts:
        paths:
            - /builds/kp.marczynski/dietify/appointments/build/libs/*.jar
            - /builds/kp.marczynski/dietify/appointments/build/classes
        expire_in: 1 day

# ionic
ionic-frontend-test:
    stage: test
    script:
        - cd /builds/kp.marczynski/dietify/ionic
        - npm install
        - npm test
    except:
        - praca-dyplomowa

latex-compilation:
    stage: build
    image: aergus/latex
    script:
        - cd /builds/kp.marczynski/dietify/documentation/latex
        - latexmk -pdf main.tex
    artifacts:
        expire_in: 1 day
        paths:
            - result.pdf
    only:
        refs:
            - praca-dyplomowa
