image: jhipster/jhipster:v6.1.2

cache:
  key: '$CI_COMMIT_REF_NAME'
  paths:
    - .gradle/
stages:
  - build
  - test
  - analyze
  - package
  - release
  - deploy

before_script:
  - export NG_CLI_ANALYTICS="false"
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - cd `pwd`/gateway
  - sh gradlew npm_install -PnodeInstall --no-daemon
  - cd `pwd`/ionic
  - npm install
  - cd `pwd`/

# gateway
gateway-gradle-compile:
  stage: build
  script:
    - sh gateway/gradlew compileJava -x check -PnodeInstall --no-daemon
  artifacts:
    paths:
      - gateway/build/classes/
      - gateway/build/generated/
    expire_in: 1 day

gateway-gradle-test:
  stage: test
  script:
    - sh gateway/gradlew test -PnodeInstall --no-daemon
  artifacts:
    reports:
      junit: gateway/build/test-results/test/TEST-*.xml
    paths:
      - gateway/build/test-results/
      - gateway/build/jacoco/
    expire_in: 1 day

gateway-gradle-integration-test:
  stage: test
  script:
    - sh gateway/gradlew integrationTest -PnodeInstall --no-daemon
  artifacts:
    reports:
      junit: gateway/build/test-results/integrationTest/TEST-*.xml
    paths:
      - gateway/build/test-results/
      - gateway/build/jacoco/
    expire_in: 1 day

gateway-frontend-test:
  stage: test
  script:
    - sh gateway/gradlew npm_run_test -PnodeInstall --no-daemon
  artifacts:
    reports:
      junit: gateway/build/test-results/TESTS-results-jest.xml
    paths:
      - gateway/build/test-results/
      - gateway/build/jacoco/
    expire_in: 1 day

gateway-gradle-package:
  stage: package
  script:
    - sh gateway/gradlew bootJar -Pprod -x check --no-daemon
  artifacts:
    paths:
      - gateway/build/libs/*.jar
      - gateway/build/classes
    expire_in: 1 day

# products
products-gradle-compile:
    stage: build
    script:
        - sh products/gradlew compileJava -x check -PnodeInstall --no-daemon
    artifacts:
        paths:
            - products/build/classes/
            - products/build/generated/
        expire_in: 1 day

products-gradle-test:
    stage: test
    script:
        - sh products/gradlew test -PnodeInstall --no-daemon
    artifacts:
        reports:
            junit: products/build/test-results/test/TEST-*.xml
        paths:
            - products/build/test-results/
            - products/build/jacoco/
        expire_in: 1 day

products-gradle-integration-test:
    stage: test
    script:
        - sh products/gradlew integrationTest -PnodeInstall --no-daemon
    artifacts:
        reports:
            junit: products/build/test-results/integrationTest/TEST-*.xml
        paths:
            - products/build/test-results/
            - products/build/jacoco/
        expire_in: 1 day

products-gradle-package:
    stage: package
    script:
        - sh products/gradlew bootJar -Pprod -x check --no-daemon
    artifacts:
        paths:
            - products/build/libs/*.jar
            - products/build/classes
        expire_in: 1 day

# recipes
recipes-gradle-compile:
    stage: build
    script:
        - sh recipes/gradlew compileJava -x check -PnodeInstall --no-daemon
    artifacts:
        paths:
            - recipes/build/classes/
            - recipes/build/generated/
        expire_in: 1 day

recipes-gradle-test:
    stage: test
    script:
        - sh recipes/gradlew test -PnodeInstall --no-daemon
    artifacts:
        reports:
            junit: recipes/build/test-results/test/TEST-*.xml
        paths:
            - recipes/build/test-results/
            - recipes/build/jacoco/
        expire_in: 1 day

recipes-gradle-integration-test:
    stage: test
    script:
        - sh recipes/gradlew integrationTest -PnodeInstall --no-daemon
    artifacts:
        reports:
            junit: recipes/build/test-results/integrationTest/TEST-*.xml
        paths:
            - recipes/build/test-results/
            - recipes/build/jacoco/
        expire_in: 1 day

recipes-gradle-package:
    stage: package
    script:
        - sh recipes/gradlew bootJar -Pprod -x check --no-daemon
    artifacts:
        paths:
            - recipes/build/libs/*.jar
            - recipes/build/classes
        expire_in: 1 day

# mealplans
mealplans-gradle-compile:
    stage: build
    script:
        - sh mealplans/gradlew compileJava -x check -PnodeInstall --no-daemon
    artifacts:
        paths:
            - mealplans/build/classes/
            - mealplans/build/generated/
        expire_in: 1 day

mealplans-gradle-test:
    stage: test
    script:
        - sh mealplans/gradlew test -PnodeInstall --no-daemon
    artifacts:
        reports:
            junit: mealplans/build/test-results/test/TEST-*.xml
        paths:
            - mealplans/build/test-results/
            - mealplans/build/jacoco/
        expire_in: 1 day

mealplans-gradle-integration-test:
    stage: test
    script:
        - sh mealplans/gradlew integrationTest -PnodeInstall --no-daemon
    artifacts:
        reports:
            junit: mealplans/build/test-results/integrationTest/TEST-*.xml
        paths:
            - mealplans/build/test-results/
            - mealplans/build/jacoco/
        expire_in: 1 day

mealplans-gradle-package:
    stage: package
    script:
        - sh mealplans/gradlew bootJar -Pprod -x check --no-daemon
    artifacts:
        paths:
            - mealplans/build/libs/*.jar
            - mealplans/build/classes
        expire_in: 1 day

# appointments
appointments-gradle-compile:
    stage: build
    script:
        - sh appointments/gradlew compileJava -x check -PnodeInstall --no-daemon
    artifacts:
        paths:
            - appointments/build/classes/
            - appointments/build/generated/
        expire_in: 1 day

appointments-gradle-test:
    stage: test
    script:
        - sh appointments/gradlew test -PnodeInstall --no-daemon
    artifacts:
        reports:
            junit: appointments/build/test-results/test/TEST-*.xml
        paths:
            - appointments/build/test-results/
            - appointments/build/jacoco/
        expire_in: 1 day

appointments-gradle-integration-test:
    stage: test
    script:
        - sh appointments/gradlew integrationTest -PnodeInstall --no-daemon
    artifacts:
        reports:
            junit: appointments/build/test-results/integrationTest/TEST-*.xml
        paths:
            - appointments/build/test-results/
            - appointments/build/jacoco/
        expire_in: 1 day

appointments-gradle-package:
    stage: package
    script:
        - sh appointments/gradlew bootJar -Pprod -x check --no-daemon
    artifacts:
        paths:
            - appointments/build/libs/*.jar
            - appointments/build/classes
        expire_in: 1 day

# ionic
ionic-frontend-test:
    stage: test
    script:
        - cd `pwd`/ionic
        - npm test
