version: '2'
services:
  gateway-app:
    image: gateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://dietify-postgresql:5432/dietify'
      - JHIPSTER_SLEEP=30
      - 'SPRING_DATA_JEST_URI=http://dietify-elasticsearch:9200'
      - 'SPRING_ELASTICSEARCH_REST_URIS=http://dietify-elasticsearch:9200'
      - JHIPSTER_REGISTRY_PASSWORD=admin
    ports:
      - '8080:8080'

  products-app:
    image: products
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://dietify-postgresql:5432/dietify'
      - JHIPSTER_SLEEP=30
      - 'SPRING_DATA_JEST_URI=http://dietify-elasticsearch:9200'
      - 'SPRING_ELASTICSEARCH_REST_URIS=http://dietify-elasticsearch:9200'
      - JHIPSTER_REGISTRY_PASSWORD=admin

  recipes-app:
    image: recipes
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://dietify-postgresql:5432/dietify'
      - JHIPSTER_SLEEP=30
      - 'SPRING_DATA_JEST_URI=http://dietify-elasticsearch:9200'
      - 'SPRING_ELASTICSEARCH_REST_URIS=http://dietify-elasticsearch:9200'
      - JHIPSTER_REGISTRY_PASSWORD=admin

  mealplans-app:
    image: mealplans
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://dietify-postgresql:5432/dietify'
      - JHIPSTER_SLEEP=30
      - 'SPRING_DATA_JEST_URI=http://dietify-elasticsearch:9200'
      - 'SPRING_ELASTICSEARCH_REST_URIS=http://dietify-elasticsearch:9200'
      - JHIPSTER_REGISTRY_PASSWORD=admin

  appointments-app:
    image: appointments
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://dietify-postgresql:5432/dietify'
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin

  dietify-postgresql:
    image: 'postgres:11.3'
    environment:
      - POSTGRES_USER=dietify
      - POSTGRES_PASSWORD=
    ports:
        - '5432:5432'

  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry

  mail-server:
    image: djfarrelly/maildev
    ports:
        - 1080:1080
        - 1025:25

#  dietify-elasticsearch:
#      image: 'docker.elastic.co/elasticsearch/elasticsearch:6.4.3'
#      environment:
#          - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
#          - discovery.type=single-node
#
#  jhipster-elasticsearch:
#    extends:
#      file: jhipster-console.yml
#      service: jhipster-elasticsearch
#  jhipster-logstash:
#    extends:
#      file: jhipster-console.yml
#      service: jhipster-logstash
#    depends_on:
#      - jhipster-elasticsearch
#  jhipster-console:
#    extends:
#      file: jhipster-console.yml
#      service: jhipster-console
#    depends_on:
#      - jhipster-elasticsearch
#  jhipster-import-dashboards:
#    extends:
#      file: jhipster-console.yml
#      service: jhipster-import-dashboards
#    depends_on:
#      - jhipster-elasticsearch
