version: '2'
services:
  recipes-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/recipes/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=recipes
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
